server:
  port: 9907
spring:
  application:
    name: leadnews-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: d0442d84-d7d4-40dc-a3b9-eb46435f39c7
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/leadnews_search?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.usian.model.search.pojos

#取消对elastsearch的健康检查
management:
  health:
    elasticsearch:
      enabled: false
#自定义elasticsearch连接配置
elasticsearch:
  host: 127.0.0.1
  port: 9200