server:
  port: 9101
spring:
  application:
    name: leadnews-admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/leadnews_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.usian.model.admin.pojos
  configuration:
    map-underscore-to-camel-case: false  #是否关闭驼峰到下划线的映射
    cache-enabled: false  #是否开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句