server:
  port: 9105
spring:
  application:
    name: leadnews-canal
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    username: guest
    password: guest
    virtual-host: /
canal:
  host: 192.168.211.132
  port: 11111